# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
    inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ARMPipeline-conn'
        subscriptionId: 'e8b7e2aa-ef92-428f-8e31-65ffcddfa105'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'ARMPipeline-rg'
        location: 'Central US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Madhur2908/ARMPipeline-repo/main/template.txt'
        overrideParameters: '-projectName ARM_IAC.'
        deploymentMode: 'Incremental'
        deploymentName: 'DeployPipelineTemplate'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
